id: 958915844b296815c246
bug_link: https://syzkaller.appspot.com/bug?extid=958915844b296815c246
title: 'upstream boot error: general protection fault in do_mount_root'
source_page: https://syzkaller.appspot.com/upstream/fixed
trigger_commit: d1eef1c619749b2a57e514a3fa67d9a516ffa919
fix_commit: 7de7de7ca0ae0fc70515ee3154af33af75edae2c
datetime: '2019-12-16T08:42:39-08:00'
fix_commit_message: 'Fix root mounting with no mount options


  The "trivial conversion" in commit cccaa5e33525 ("init: use do_mount()

  instead of ksys_mount()") was totally broken, since it didn''t handle the

  case of a NULL mount data pointer.  And while I had "tested" it (and

  presumably Dominik had too) that bug was hidden by me having options.


  Cc: Dominik Brodowski <linux@dominikbrodowski.net>

  Cc: Arnd Bergmann <arnd@arndb.de>

  Reported-by: Ondřej Jirman <megi@xff.cz>

  Reported-by: Guenter Roeck <linux@roeck-us.net>

  Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>

  Reported-and-tested-by: Borislav Petkov <bp@suse.de>

  Tested-by: Chris Clayton <chris2553@googlemail.com>

  Tested-by: Eric Biggers <ebiggers@kernel.org>

  Tested-by: Geert Uytterhoeven <geert@linux-m68k.org>

  Tested-by: Guido Günther <agx@sigxcpu.org>

  Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

  '
submodule:
- init
hunk_count: 2
covered_count: 2
