id: 34a8ffb71f7fb32ecca2
bug_link: https://syzkaller.appspot.com/bug?extid=34a8ffb71f7fb32ecca2
title: WARNING in __blkdev_put (2)
source_page: https://syzkaller.appspot.com/upstream/fixed
trigger_commit: fd03177c33b287c6541f4048f1d67b7b45a1abc9
fix_commit: e91455bad5cff40a8c232f2204a5104127e3fec2
datetime: '2019-08-08T07:37:03-06:00'
fix_commit_message: 'bdev: Fixup error handling in blkdev_get()


  Commit 89e524c04fa9 ("loop: Fix mount(2) failure due to race with

  LOOP_SET_FD") converted blkdev_get() to use the new helpers for

  finishing claiming of a block device. However the conversion botched the

  error handling in blkdev_get() and thus the bdev has been marked as held

  even in case __blkdev_get() returned error. This led to occasional

  warnings with block/001 test from blktests like:


  kernel: WARNING: CPU: 5 PID: 907 at fs/block_dev.c:1899 __blkdev_put+0x396/0x3a0


  Correct the error handling.


  CC: stable@vger.kernel.org

  Fixes: 89e524c04fa9 ("loop: Fix mount(2) failure due to race with LOOP_SET_FD")

  Signed-off-by: Jan Kara <jack@suse.cz>

  Signed-off-by: Jens Axboe <axboe@kernel.dk>

  '
submodule:
- fs
hunk_count: 1
covered_count: 0
