id: f74aa89114a236643919
bug_link: https://syzkaller.appspot.com/bug?extid=f74aa89114a236643919
title: general protection fault in do_blk_trace_setup
source_page: https://syzkaller.appspot.com/upstream/fixed
trigger_commit: 1e294970fc00f45c1f17fb442c26a7e3fc9789b1
fix_commit: 1d1cf156dc176e30eeaced5cf1450d582d387b81
datetime: '2021-08-25T06:46:54-06:00'
fix_commit_message: 'sg: pass the device name to blk_trace_setup


  Fix a regression that passed a NULL device name to blk_trace_setup

  accidentally.


  Fixes: aebbb5831fbd ("sg: do not allocate a gendisk")

  Reported-by: syzbot+f74aa89114a236643919@syzkaller.appspotmail.com

  Signed-off-by: Christoph Hellwig <hch@lst.de>

  Reviewed-by: Max Gurtovoy <mgurtovoy@nvidia.com>

  Link: https://lore.kernel.org/r/20210825075438.1883687-1-hch@lst.de

  Signed-off-by: Jens Axboe <axboe@kernel.dk>

  '
submodule:
- drivers/scsi
hunk_count: 1
covered_count: 1
